### ISSUE TITLE
Audio Timeline Enhancement

### ISSUE THREAD

**Issue by DevSusu** [HwaYo/parrot#1]
프로토타입까지는 최대한 간단한 라이브러리를 이용해 만들고 나중에 [Timeline.js](http://timeline.knightlab.com/) 같은 것을 써서 업데이트 하기로 합시다.

**Comment by minhyeok4dev** [comment]
[wavesurfer](http://wavesurfer.fm) 에서 Regeion 플러그인 써서 해결??

**Comment by angdev** [comment]
일단 wavesurfer를 썼으니 추가적인 이슈가 있으면 다시 열어주세요.
