### ISSUE TITLE
노트에 책갈피를 같이 보여주기

### ISSUE THREAD

**Issue by DevSusu** [HwaYo/parrot#47]
녹음 도중
- 책갈피를 등록하면 현재 입력하던 곳에 `<a href="#" title="10:00" data-...="bookmark_id">10:00 중요</a>` 와 같은 태그를 추가.
  ![screen shot 2015-04-08 at 10 27 57](https://cloud.githubusercontent.com/assets/5153025/7037224/09f9d998-ddda-11e4-807b-a9aae83c5a0e.png)

재생
- 링크를 클릭하면 해당 책갈피로 이동
- 책갈피 시점 변경은 불가능?

여기서 문제점은 `medium editor`의 상태인데, 수정 상태에서는 링크를 클릭하는 것이 링크를 수정하는 모양이 나오게 된다. [에디터 옵션](https://github.com/daviferreira/medium-editor#core-options)중 ``disableEditing`으로 수정 가능 불가능을 설정할 수 있는데 통째로 수정을 못하게 되므로 어떻게 할지 고민입니다.

좋은 의견 있으신분 있나요 ㅠㅠ

**Comment by angdev** [comment]
좋은 의견 같은 거 없음

**Comment by shaynekang** [comment]
음. UX적인 문제가 있다는 걸 이야기하는거죠?

책갈피를 노트에 넣으면 우측에 glyficon 스타일의 재생 버튼을 넣으면 어떨까요? 책갈피를 클릭라면 수정할 수 있고, 재생 버튼을 클릭하면 재생이 되는거죠. ㅎㅎ
