### ISSUE TITLE
소프트 삭제(Soft Delete) 재구현하기

### ISSUE THREAD

**Issue by shaynekang** [HwaYo/parrot#52]
현재 소프트 삭제(Soft Delete) - 레코드를 삭제할 경우 DB에서 지우지 않고 delete 플래그만 올려주는 것 - 가 구현되어 있는데, 현재 구현은 다음과 같은 실수를 할 여지가 있습니다.
- `record.destroy`를 호출하면 hard delete가 되어버림.
- 살아있는 레코드를 사용하는 모든 상황에서 `Record.remaining`을 호출해야 함. 즉 `Record.some_query_function`을 호출하면 soft delete된 record도 결과값에 같이 나옴

보통은 1. destroy를 재구현하고 2. 레일즈의 [default_scope](http://guides.rubyonrails.org/active_record_querying.html#applying-a-default-scope)를 이용해 언제나 `deleted == false`한 레코드만 나오도록 구현할 것을 권장합니다.

또는 그냥 [Gem을 사용하는 것](https://www.ruby-toolbox.com/categories/Active_Record_Soft_Delete)을 권장하죠.(..)
편한 쪽으로 고쳐주시면 됩니다. ㅋ

**Comment by shaynekang** [comment]
근데 소프트 삭제를 구현한 이유가 있나요? ㅎㄷ

**Comment by angdev** [comment]
이제 동기화가 들어가서 필요하게 됐습니다. 제가 구현하고 있습니다.

**Comment by shaynekang** [comment]
:+1:

**Comment by angdev** [comment]
#106 에서 구현했습니다.
