### ISSUE TITLE
책갈피 관련 기획안 재검토

### ISSUE THREAD

**Issue by minhyeok4dev** [HwaYo/parrot#8]
프로토타입에서는 노트에 타임스탬프를 넣는 것으로 했으나, 정확한 히스토리를 보고, 도중에 수정 등의 기능이 있도록 하는 것이 좋을 것이라고 생각됩니다. 다같이 생각해보도록 합시다.

**Comment by angdev** [comment]
- #18 
- 책갈피 수정 삭제를 어떻게 할 것인가?

정도가 현재 논의되어야 할 문제입니다.

**Comment by angdev** [comment]
일단 #47 로 합의하였고 책갈피 수정/삭제는 현재 불가합니다. 이후에 책갈피 관련 기획안을 수정할 때 다시 열도록 합시다.
