### ISSUE TITLE
음파와 북마크가 모두 안 뜸

### ISSUE THREAD

**Issue by shaynekang** [HwaYo/parrot#91]
![screen shot 2015-04-14 at 11 34 22 pm](https://cloud.githubusercontent.com/assets/528040/7139010/d2015c26-e2fe-11e4-969a-dea58d2ba79c.png)

http://loroclip.herokuapp.com/records/36 에서 나온 문제네요.
음파도 북마크도 모두 나오지 않아요. ㅠㅠ

**Comment by minhyeok4dev** [comment]
재현 조건이 뭐였을까요
